### ISSUE TITLE
Can this be configured to work with other global cookie lawas like COPPA, e Privacy, POPPIA, with Geo-blocking, Do Not Track (DNT), etc?

### ISSUE THREAD

**Issue by tradegong** [replete/biscuitman#3]
Can this be configured to work with other global cookie lawas like COPPA, e Privacy, POPPIA, with Geo-blocking, Do Not Track (DNT), etc? Is there a way I can achieve these with this software? I need to configure global/ regional lwa, geo-blocking, dnt, COPPA, etc, to make my website truly global. How can I go about doing this?
Thanks for your help.

**Comment by replete** [comment]
Geoblocking and region specificity requires development of a server-side component to lookup the IP address against a geocoding database, biscuitman is only a client-side solution which restricts and does not address this, but a developer could integrate with this by only serving the cookie notice depending on the IP.

There is a feature that allows you to autoconsent if the users timezone is European, but this is not as reliable as geocoding but is a bit of a hack. 

The way you a developer could do this, on your server would be something like:
- load geolite2 geocoding db into memory
- check IP on first visit
- if: location/region matches a cookie requirement, then include biscuitman formatted  trackers + biscuitman config + biscuitman js
- else: include trackers normally, don't include biscuitman

**Comment by tradegong** [comment]
Okay.  Tnx for your prompt response.  Is it possible to install it via Google Tag Manager and link from there to a custom javascript of my own, containing all those functions configured into it.
Kindly advise on this please.  Tnx

**Comment by replete** [comment]
With biscuitman scenario, you wouldn't even load google tag manager on your site until you got consent because Google's code kind of does what it wants. There is a consent feature with Google Analytics that can be set up, but its complicated, and this project sidesteps all that.

If you need geo-coded cookie consent, there is no shortcut, you must either get a developer to implement something like I suggested or pay for one of those cookie consent management platforms to handle it for you.

What software is your website using?

**Comment by tradegong** [comment]
I have three websites I wish to implement it on, using sofwares, namely WordPress, phpbb and Modesy. 
If this can't be implemented via gtm, how else can it be done? Through a direct implementation in the header script?

**Comment by replete** [comment]
I would recommend, you slow down, stop spamming all these consent managers github issues and wasting peoples time, and just read the documentation to understand how these consent managers work and pick one that meets your needs. I've told you explicitly what you'd need to get what you want in my first response, server-side development.. geolite integration.

**Comment by tradegong** [comment]
You are insulting my person!! Why would you say that I am spamming? Please, I would advise that you moderate your use of words. Don't I have the right to ask questions about anything that catches my interest? That I asked a question should not automatically subordinate me to you or subject me to your insult!!

**Comment by replete** [comment]
I told you explicitly how to implement what you wanted. You are welcome. Then you ask more questions without even acknowledging my answer, as if you didn't read it. This combined with your copy paste responses on every consent manager on github (when the answers are literally in the READMEs) tells me that you expect other people to solve the problem for you, and that is what prompted my comment. Nothing personal.
